# Generated by Django 2.2.3 on 2019-07-24 08:13

import constants
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[(constants.UserTypes('Super Admin'), 'Super Admin'), (constants.UserTypes('Admin'), 'Admin'), (constants.UserTypes('User'), 'User')], max_length=5)),
                ('loginStatus', models.CharField(choices=[(constants.LoginStatus('Logged'), 'Logged'), (constants.LoginStatus('Not Logged'), 'Not Logged')], max_length=5)),
                ('status', models.CharField(choices=[(constants.Status('Pending'), 'Pending'), (constants.Status('Confirmed'), 'Confirmed')], max_length=5)),
                ('activation', models.CharField(choices=[(constants.Activation('Activated'), 'Activated'), (constants.Activation('Deactivated'), 'Deactivated')], max_length=5)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[(constants.Gender('Male'), 'Male'), (constants.Gender('Female'), 'Female')], max_length=5)),
                ('profile', models.FileField(upload_to='static/images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
