# Generated by Django 2.2.3 on 2019-07-24 08:40

import constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('Male', constants.Gender('Male')), ('Female', constants.Gender('Female'))], max_length=5),
        ),
    ]
