# Generated by Django 2.2.3 on 2019-07-24 08:44

import constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190724_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[(constants.Gender('Male'), constants.Gender('Male')), (constants.Gender('Female'), constants.Gender('Female'))], max_length=5),
        ),
    ]
