# Generated by Django 2.2.3 on 2019-07-24 08:52

import constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190724_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='activation',
            field=models.CharField(choices=[('Activated', constants.Activation('Activated')), ('Deactivated', constants.Activation('Deactivated'))], max_length=5),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('Male', constants.Gender('Male')), ('Female', constants.Gender('Female'))], max_length=5),
        ),
    ]
