# Generated by Django 2.2.3 on 2019-07-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20190724_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='activation',
            field=models.CharField(choices=[('Activated', 'Activated'), ('Deactivated', 'Deactivated')], max_length=12),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=12),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='loginStatus',
            field=models.CharField(choices=[('Logged', 'Logged'), ('Not Logged', 'Not Logged')], max_length=12),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('Super Admin', 'Super Admin'), ('Admin', 'Admin'), ('User', 'User')], max_length=12),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], max_length=12),
        ),
    ]
