# Generated by Django 2.2.3 on 2019-07-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190725_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile',
            field=models.ImageField(upload_to='images'),
        ),
    ]
