# Generated by Django 2.2.3 on 2019-07-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20190725_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
